package com.infy.googleai.dto;

/**
 * Response payload from the spending insight endpoint.
 * insight contains a natural-language sentence generated by Gemini.
 */
public record InsightResponse(String insight) {}
