version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # port where kafka talks to zookeeper
      ZOOKEEPER_TICK_TIME: 2000 # time interval between heartbeats
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper # ← Zookeeper must start FIRST
    ports:
      - "9092:9092" # ← Your Spring Boot apps connect here
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # ← tell kafka where zookeeper is
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT # ↑ Just says both listeners use plain text (no SSL) — no encryption for local dev
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092 # ↑ TWO listeners — this is the most important part (explained below)
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT # ↑ Brokers talk to each other using PLAINTEXT listener
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
