/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Luminal Ivory (light) — primary colour system
        'primary-fixed-dim':        '#b8c3ff',
        'on-primary-container':     '#efefff',
        'on-tertiary':              '#ffffff',
        'inverse-surface':          '#2e3132',
        'primary-fixed':            '#dde1ff',
        'on-secondary':             '#ffffff',
        'inverse-on-surface':       '#f0f1f3',
        'primary-container':        '#2e5bff',
        'secondary':                '#515f74',
        'surface-container-high':   '#e7e8ea',
        'on-error-container':       '#93000a',
        'on-surface-variant':       '#434656',
        'surface':                  '#f8f9fb',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#0035be',
        'surface-bright':           '#f8f9fb',
        'on-secondary-container':   '#57657a',
        'on-primary':               '#ffffff',
        'outline':                  '#747688',
        'surface-variant':          '#e1e2e4',
        'on-error':                 '#ffffff',
        'tertiary':                 '#993100',
        'tertiary-fixed':           '#ffdbcf',
        'on-secondary-fixed-variant':'#3a485b',
        'on-background':            '#191c1e',
        'error':                    '#ba1a1a',
        'on-secondary-fixed':       '#0d1c2e',
        'secondary-fixed-dim':      '#b9c7df',
        'surface-container':        '#edeef0',
        'background':               '#f8f9fb',
        'secondary-container':      '#d5e3fc',
        'tertiary-fixed-dim':       '#ffb59b',
        'on-tertiary-fixed':        '#380d00',
        'outline-variant':          '#c4c5d9',
        'tertiary-container':       '#c24100',
        'on-primary-fixed':         '#001356',
        'secondary-fixed':          '#d5e3fc',
        'surface-container-low':    '#f2f4f6',
        'surface-dim':              '#d9dadc',
        'on-surface':               '#191c1e',
        'primary':                  '#0040e0',
        'error-container':          '#ffdad6',
        'on-tertiary-fixed-variant':'#812800',
        'on-tertiary-container':    '#ffece6',
        'inverse-primary':          '#b8c3ff',
        'surface-tint':             '#124af0',
        'surface-container-highest':'#e1e2e4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
        sans:     ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
