package com.infy.googleai.service;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

/**
 * Uses the Google Gemini model to generate human-readable spending insights
 * from structured financial summary data provided by AnalysisMS.
 */
@Service
public class SpendingInsightService {

    private final ChatClient chatClient;

    public SpendingInsightService(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }

    /**
     * Given a structured text summary of spending data, returns a concise,
     * friendly, actionable insight paragraph generated by Gemini.
     *
     * @param spendingSummary  pre-formatted spending summary (produced by AnalysisMS)
     * @return AI-generated insight string
     */
    public String generateInsight(String spendingSummary) {
        String prompt = """
                You are a smart personal finance advisor for an expense management app.
                Analyse the following spending summary and write 2-3 concise, friendly,
                actionable sentences in plain English.
                
                Rules:
                - Mention the top spending category and any notable percentage change.
                - If a category increased significantly (>20%%), warn the user.
                - If spending decreased, give a positive reinforcement.
                - End with one short tip to improve savings.
                - Do NOT use bullet points. Write as flowing sentences.
                - Keep total response under 80 words.
                
                Spending Summary:
                %s
                """.formatted(spendingSummary);

        return chatClient.prompt()
                .user(prompt)
                .call()
                .content()
                .trim();
    }
}
